#!/usr/bin/env python3
"""Roll old shared_memory.md sections into monthly archive files.

Memory that only grows eventually poisons every session — this tool is the shrink step.
Entries in 00_SELF/memory/shared_memory.md must start with a `## YYYY-MM-DD` header
(see the entry-format note in that file). Sections older than --keep-months are moved to
00_SELF/memory/archive/shared_memory_YYYY-MM.md and archive/INDEX.md is regenerated.
A timestamped .bak backup of shared_memory.md is written before any change.

Usage (from the workspace root):
    python3 tools/split_shared_memory.py --dry-run
    python3 tools/split_shared_memory.py                 # keep current + previous month
    python3 tools/split_shared_memory.py --keep-months 3
"""

import argparse
import re
import shutil
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MEMORY_FILE = REPO_ROOT / "00_SELF" / "memory" / "shared_memory.md"
ARCHIVE_DIR = MEMORY_FILE.parent / "archive"
INDEX_FILE = ARCHIVE_DIR / "INDEX.md"

HEADER_PATTERN = re.compile(r"^## (\d{4})-(\d{2})-\d{2}\b")


def parse_sections(content: str):
    """Split into sections. year_month=None marks the intro block above the first entry."""
    sections = []
    current = {"year_month": None, "lines": []}
    for line in content.splitlines(keepends=True):
        m = HEADER_PATTERN.match(line)
        if m:
            if current["lines"]:
                sections.append(current)
            current = {"year_month": f"{m.group(1)}-{m.group(2)}", "lines": [line]}
        else:
            current["lines"].append(line)
    if current["lines"]:
        sections.append(current)
    return sections


def count_sections_in_file(path: Path) -> int:
    if not path.exists():
        return 0
    return sum(1 for line in path.read_text(encoding="utf-8").splitlines()
               if HEADER_PATTERN.match(line))


def update_index(now: datetime):
    files = sorted(ARCHIVE_DIR.glob("shared_memory_*.md"), reverse=True)
    lines = [
        "# Shared Memory Archive Index\n\n",
        f"> Last updated: {now.strftime('%Y-%m-%d %H:%M:%S')}\n",
        "> Auto-generated by tools/split_shared_memory.py\n\n",
        "| Month | File | Sections |\n|----|------|---------|\n",
    ]
    for f in files:
        ym = f.stem.replace("shared_memory_", "")
        lines.append(f"| {ym} | [{f.name}]({f.name}) | {count_sections_in_file(f)} |\n")
    INDEX_FILE.write_text("".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="print the plan, change nothing")
    parser.add_argument("--keep-months", type=int, default=2,
                        help="months to keep in shared_memory.md (default 2 = this month + last)")
    args = parser.parse_args()

    if not MEMORY_FILE.exists():
        print(f"not found: {MEMORY_FILE}")
        return

    content = MEMORY_FILE.read_text(encoding="utf-8")
    sections = parse_sections(content)
    now = datetime.now()

    keep_yms = set()
    y, m = now.year, now.month
    for _ in range(args.keep_months):
        keep_yms.add(f"{y:04d}-{m:02d}")
        m -= 1
        if m == 0:
            y, m = y - 1, 12

    intro_lines, keep = [], []
    archive_groups: dict = {}
    for s in sections:
        if s["year_month"] is None:
            intro_lines.extend(s["lines"])
        elif s["year_month"] in keep_yms:
            keep.append(s)
        else:
            archive_groups.setdefault(s["year_month"], []).append(s)

    print(f"today: {now.strftime('%Y-%m-%d')}")
    print(f"keeping months: {sorted(keep_yms, reverse=True)} ({len(keep)} sections)")

    if not archive_groups:
        print("nothing to move — all sections are within the keep window.")
        return

    print("\nto archive:")
    for ym, secs in sorted(archive_groups.items(), reverse=True):
        existing = count_sections_in_file(ARCHIVE_DIR / f"shared_memory_{ym}.md")
        suffix = f"append to existing ({existing})" if existing else "new file"
        print(f"  {ym}: {len(secs)} sections -> {suffix}")

    if args.dry_run:
        print("\n[DRY RUN] no changes made.")
        return

    backup = MEMORY_FILE.with_suffix(f".md.bak.{now.strftime('%Y%m%d_%H%M%S')}")
    shutil.copy(MEMORY_FILE, backup)
    print(f"\nbackup: {backup.name}")

    ARCHIVE_DIR.mkdir(exist_ok=True)
    for ym, secs in archive_groups.items():
        archive_file = ARCHIVE_DIR / f"shared_memory_{ym}.md"
        if archive_file.exists():
            existing = archive_file.read_text(encoding="utf-8")
            if not existing.endswith("\n"):
                existing += "\n"
        else:
            existing = f"# Shared Memory Archive — {ym}\n\n"
        existing += "".join("".join(s["lines"]) for s in secs)
        archive_file.write_text(existing, encoding="utf-8")
        print(f"  -> {archive_file.name} (+{len(secs)} sections)")

    MEMORY_FILE.write_text("".join(intro_lines) + "".join("".join(s["lines"]) for s in keep),
                           encoding="utf-8")
    print(f"\nshared_memory.md rewritten: {len(keep)} sections kept")
    update_index(now)
    print("INDEX.md updated")


if __name__ == "__main__":
    main()
